export const TIME_TRACKING_CHANGED = 'TIME_TRACKING_CHANGED';
export type TIME_TRACKING_CHANGED = typeof TIME_TRACKING_CHANGED;

export const MANAGE_PROJECTS = 'MANAGE_PROJECTS';
export type MANAGE_PROJECTS = typeof MANAGE_PROJECTS;

export const ACTIVATE_PROJECT = 'ACTIVATE_PROJECT';
export type ACTIVATE_PROJECT = typeof ACTIVATE_PROJECT;