export const TIME_TRACKING_CHANGED = 'TIME_TRACKING_CHANGED';
export type TIME_TRACKING_CHANGED = typeof TIME_TRACKING_CHANGED;

export const MANAGE_PROJECTS = 'MANAGE_PROJECTS';
export type MANAGE_PROJECTS = typeof MANAGE_PROJECTS;